sbc_monitor/urls.py
from django.urls import path
from sbc_monitor import views

app_name="sbc_monitor"

urlpatterns = [    
    path('test/', views.test, name='test'),
    path('test/<int:id>', views.test2),
]

sbc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from sbc_monitor import urls as sbc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(sbc_urls)), 
]

sbc_monitor/models.py
from django.db import models

# Create your models here.


class SingleBoardComputer(models.Model):
    """ Таблица подключавшихся одноплатных компьютеров """
    name = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(
        verbose_name="Описание", blank=True, null=True)

    def __str__(self):
        return self.name


class Status(models.Model):
    """ Таблица состояний одноплатных компьютеров """
    sbc = models.ForeignKey(SingleBoardComputer, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="Дата подключения/отключения")
    real_address = models.GenericIPAddressField(
        null=True, blank=True, verbose_name="Реальный адрес")
    virtual_address = models.GenericIPAddressField(
        null=True, blank=True, verbose_name="Виртуальный адрес")

    def __str__(self):
        return str(self.updated) + " " + str(self.sbc.name)

sbc_monitor/views.py
from django.shortcuts import render
from .models import SingleBoardComputer, Status
# Create your views here.



def test(request):
  client_list = SingleBoardComputer.objects.all().values("id","name")
  return render(request, 'sbc_monitor/content_fills.html', {"client_list": client_list, })

def test2(request, id):  
  client_list = SingleBoardComputer.objects.all().values("id","name")
  client = SingleBoardComputer.objects.get(id=id)
  log_client = Status.objects.filter(sbc=id).order_by("-updated")
  status = log_client.first() # !!! log_client должен быть отсортирован!
  
  return render(request, 'sbc_monitor/content_fills.html', {
    "client_list": client_list, 
    "log_client":log_client,
    "client":client,    
    "status":status,
  })

sbc_monitor/templates/sbc_monitor/bas2e.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% bootstrap_css %}    
    {% bootstrap_jquery %}
    {% bootstrap_javascript %}
    <style>
body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
}

p {
    font-family: 'Poppins', sans-serif;
    font-size: 1.1em;
    font-weight: 300;
    line-height: 1.7em;
    color: #999;
}

a,
a:hover,
a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
}

.navbar {
    padding: 15px 10px;
    background: #fff;
    border: none;
    border-radius: 0;
    margin-bottom: 40px;
    box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
}

.navbar-btn {
    box-shadow: none;
    outline: none !important;
    border: none;
}

.line {
    width: 100%;
    height: 1px;
    border-bottom: 1px dashed #ddd;
    margin: 40px 0;
}

/* ---------------------------------------------------
    SIDEBAR STYLE
----------------------------------------------------- */

.wrapper {
    display: flex;
    width: 100%;
}

#sidebar {
    width: 250px;
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    z-index: 999;
    background: #7386D5;
    color: #fff;
    transition: all 0.3s;
}

#sidebar.active {
    margin-left: -250px;
}

#sidebar .sidebar-header {
    padding: 20px;
    background: #6d7fcc;
}

#sidebar ul.components {
    padding: 20px 0;
    border-bottom: 1px solid #47748b;
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
}

#sidebar ul li a:hover {
    color: #7386D5;
    background: #fff;
}

#sidebar ul li.active>a,
a[aria-expanded="true"] {
    color: #fff;
    background: #6d7fcc;
}

a[data-toggle="collapse"] {
    position: relative;
}

.dropdown-toggle::after {
    display: block;
    position: absolute;
    top: 50%;
    right: 20px;
    transform: translateY(-50%);
}

ul ul a {
    font-size: 0.9em !important;
    padding-left: 30px !important;
    background: #6d7fcc;
}

ul.CTAs {
    padding: 20px;
}

ul.CTAs a {
    text-align: center;
    font-size: 0.9em !important;
    display: block;
    border-radius: 5px;
    margin-bottom: 5px;
}

a.download {
    background: #fff;
    color: #7386D5;
}

a.article,
a.article:hover {
    background: #6d7fcc !important;
    color: #fff !important;
}

/* ---------------------------------------------------
    CONTENT STYLE
----------------------------------------------------- */

#content {
    width: calc(100% - 250px);
    padding: 40px;
    min-height: 100vh;
    transition: all 0.3s;
    position: absolute;
    top: 0;
    right: 0;
}

#content.active {
    width: 100%;
}

/* ---------------------------------------------------
    MEDIAQUERIES
----------------------------------------------------- */

@media (max-width: 768px) {
    #sidebar {
        margin-left: -250px;
    }
    #sidebar.active {
        margin-left: 0;
    }
    #content {
        width: 100%;    
    }
    #content.active {
        width: calc(100% - 250px);
    }
    #sidebarCollapse span {
        display: none;
    }
}

    </style>

    <script type="text/javascript">
        finction getCSRFToken(){
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        window.csrf_token = getCSRFToken();
    </script>
    
    <title>
    
    {% block title %}
    {% endblock %}

    </title>
</head>
<body>

    {% comment %} {% block menu %} {% endcomment %}
     {% comment %} {% include  'sbc_monitor/menu.html' %} {% endcomment %}

    {% comment %} {% endblock menu%} {% endcomment %}
  <header class="navbar navbar-light bg-light">
  weqwe
  </header>
  {% comment %} <div class="container-fluid">
    <div class="row">
      <div class="col col-md-3 bg-dark">qwe</div>
      <div class="col bg-primary">qwe</div>
    </div>
  </div> {% endcomment %}

<div class="wrapper">

<!-- Sidebar -->
<nav id="sidebar" class="bg-primary">
    qwe
</nav>

<!-- Page Content -->
<div id="content" class="bg-dark">
    <!-- We'll fill this with dummy content -->
    qe
</div>

</div>       


  
    
</body>
</html>

sbc_monitor/templates/sbc_monitor/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% bootstrap_css %}    
    {% bootstrap_jquery %}
    {% bootstrap_javascript %}
    <title>Document</title>
    <style>
        html,
        body {
            height: 100%;
        }
    </style>
</head>

<body">
    <div class="container-fluid h-100">
        <div class="row">
            <nav class="col navbar navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'sbc_monitor:test' %}">SBC Monitor</a>
                <button class="btn btn-link navbar-toggler d-lg-none collapsed" type="button" data-toggle="collapse"
                    data-target="#collapseOne" aria-controls="collapseOne" aria-expanded="false"
                    aria-label="Toggle docs navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </nav>
        </div>



        <div class="row flex-x1-nowrap navbar-expand-lg h-100">

            <div class=" col-lg-2 col-xl-2 navbar-collapse collapse bg-light p-0 align-items-stretch"
                style="overflow: auto;" id="collapseOne">

                <div class="container-fluid">
                    <div class="row">
                        <div class="col col-12 list-group p-0">
                        {% comment %} list-group-item-action {% endcomment %}
                        {% comment %} <a href="#" class="p-2 ">Flex itasdasdem 1</a> {% endcomment %}
                            {% block client_list %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col col-lg-10 col-xl-10 mt-2"> 
                {% block content %}
                {% endblock %}                
            </div>
        </div>
    </div>
    </body>


</html>


<!-- <div  class="navbar-collapse collapse flex-column"> -->
<!-- <a class="nav-link active" href="#">Active</a>
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link" href="#">Link</a>
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
<!-- <div class="list-group">
                        <li class="list-group-item ">Cras </li>
                        <li class="list-group-item ">Cras </li>
                    </div> -->

sbc_monitor/templates/sbc_monitor/content_fills.html
{% extends 'sbc_monitor/base.html' %}

{% block client_list %}
  {% for client_l in client_list %}
    {% if client_l.id == client.id %}
      <a href="{{client_l.id}}" class="p-2 text-dark bg-info">{{ client_l.name }}</a>
    {% else %}
      <a href="{{client_l.id}}" class="p-2 text-dark">{{ client_l.name }}</a>
    {% endif %}
    
  {% endfor %}
{% endblock %}

{% block content %} 
  
  {% if client %}
  
  {% if status.real_address %}    
      <h4>{{client.name}} <span class="badge badge-success float-right">Включен</span></h4>          
    {% else %}
      <h4>{{client.name}} <span class="badge badge-danger float-right">Выключен</span></h4>
  {% endif %}
  
  
  
  <div class="jumbotron p-3">
    <h5 style="color:#6c757d;">Описание</h5>
    <p>
      {% if client.description %}
        {{client.description}}        
        <button type="button" class="btn btn-link float-right" data-toggle="modal" data-target="#exampleModal">Редактировать</button>
        {% include 'sbc_monitor/modal.html'%}
      {% else %}
        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Добавить описание</button>        
        {% include 'sbc_monitor/modal.html'%}
      {% endif %}  
    </p>
  </div>    
  
  {% comment %} <h5 style="color:#6c757d;">Текущее состояние</h5>   {% endcomment %}
  {% comment %} <h5>Текущее состояние: <span class="badge badge-danger">Выключен</span></h5>
  <h5>Текущее состояние: <span class="badge badge-success">Включен</span></h5> {% endcomment %}
  
  
  <div class="table-responsive">
  <table class="table table-bordered table-hover ">
    <caption style="caption-side: top;"><h5>Журнал подключений<h5></caption>
    <thead class="thead-light">
      <tr>
        <th class="text-center">Дата</th>        
        <th class="text-center">Реальный адрес</th>
        <th class="text-center">Виртуальный адрес</th>        
      </tr>
    </thead>
    <tbody>
    {% for log in log_client %}
      <tr>
        <td class="text-center"> {{ log.date|date:"d.m.Y H:i:s" }}</td>        
        <td class="text-center"> {{ log.real_address }} </td>
        <td class="text-center"> {{ log.virtual_address }} </td>
      </tr>          
    {% endfor %}
    </tbody>
  </table>
  </div>
{% endif %}
{% endblock %}

sbc_monitor/templates/sbc_monitor/modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Описание для {{client.name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          {% comment %} <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div> {% endcomment %}
          <div class="form-group">
            <label for="message-text" class="col-form-label">Введите описание:</label>
            <textarea class="form-control" id="message-text">{% if client.description %}{{client.description}}{% endif %}</textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
        <button type="button" class="btn btn-primary">Сохранить</button>
      </div>
    </div>
  </div>
</div>